import { PlatformDatabase } from "@/types/platform";

export const MOCK_DATABASE: PlatformDatabase = {
  indications: [
    {
      id: "IND-001",
      name: "Systemic Lupus Erythematosus",
      description:
        "A chronic, systemic autoimmune disease characterized by multisystem inflammation, loss of self-tolerance, and aberrant autoantibody production targeting nuclear antigens.",
      therapeuticArea: "Immunology",
    },
    {
      id: "IND-002",
      name: "Hidradenitis Suppurativa",
      description:
        "A painful, debilitating chronic inflammatory skin condition characterized by recurrent, deep-seated inflammatory nodules, abscesses, draining sinus tracts, and extensive scarring in apocrine gland-bearing skin.",
      therapeuticArea: "Immunology / Dermatology",
    },
  ],
  archTargets: [
    {
      gene: "TLR7",
      ensemblId: "ENSG00000101916",
      disease: "Systemic Lupus Erythematosus",
      archVersion: "v2.4",
      swagStrength: 0.88,
      swagScore: 8.42,
      swagScoreNoClin: 7.95,
      pathwayCausal: 0.92,
      genetic: 0.85,
      pathwayGeneral: 0.78,
      clinicalMao: 0.84,
      currentDevStatus: "Phase 2",
      links: [
        "https://www.genecards.org/cgi-bin/carddisp.pl?gene=TLR7",
        "https://www.targetvalidation.org/target/ENSG00000101916",
      ],
    },
    {
      gene: "IL2",
      ensemblId: "ENSG00000109471",
      disease: "Systemic Lupus Erythematosus",
      archVersion: "v2.4",
      swagStrength: 0.79,
      swagScore: 7.64,
      swagScoreNoClin: 7.21,
      pathwayCausal: 0.86,
      genetic: 0.74,
      pathwayGeneral: 0.82,
      clinicalMao: 0.75,
      currentDevStatus: "Phase 2",
      links: [
        "https://www.genecards.org/cgi-bin/carddisp.pl?gene=IL2",
        "https://www.targetvalidation.org/target/ENSG00000109471",
      ],
    },
    {
      gene: "IL2RA",
      ensemblId: "ENSG00000134460",
      disease: "Systemic Lupus Erythematosus",
      archVersion: "v2.4",
      swagStrength: 0.81,
      swagScore: 7.82,
      swagScoreNoClin: 7.39,
      pathwayCausal: 0.84,
      genetic: 0.88,
      pathwayGeneral: 0.76,
      clinicalMao: 0.79,
      currentDevStatus: "Phase 2",
      links: [
        "https://www.genecards.org/cgi-bin/carddisp.pl?gene=IL2RA",
        "https://www.targetvalidation.org/target/ENSG00000134460",
      ],
    },
    {
      gene: "TYK2",
      ensemblId: "ENSG00000105397",
      disease: "Systemic Lupus Erythematosus",
      archVersion: "v2.4",
      swagStrength: 0.91,
      swagScore: 8.75,
      swagScoreNoClin: 8.24,
      pathwayCausal: 0.95,
      genetic: 0.93,
      pathwayGeneral: 0.89,
      clinicalMao: 0.88,
      currentDevStatus: "Phase 3",
      links: [
        "https://www.genecards.org/cgi-bin/carddisp.pl?gene=TYK2",
        "https://www.targetvalidation.org/target/ENSG00000105397",
      ],
    },
    {
      gene: "TNF",
      ensemblId: "ENSG00000232810",
      disease: "Systemic Lupus Erythematosus",
      archVersion: "v2.4",
      swagStrength: 0.94,
      swagScore: 9.12,
      swagScoreNoClin: 8.65,
      pathwayCausal: 0.91,
      genetic: 0.82,
      pathwayGeneral: 0.96,
      clinicalMao: 0.95,
      currentDevStatus: "Launched",
      links: [
        "https://www.genecards.org/cgi-bin/carddisp.pl?gene=TNF",
        "https://www.targetvalidation.org/target/ENSG00000232810",
      ],
    },
    {
      gene: "IL10",
      ensemblId: "ENSG00000136634",
      disease: "Systemic Lupus Erythematosus",
      archVersion: "v2.4",
      swagStrength: 0.76,
      swagScore: 7.35,
      swagScoreNoClin: 6.98,
      pathwayCausal: 0.79,
      genetic: 0.71,
      pathwayGeneral: 0.85,
      clinicalMao: 0.72,
      currentDevStatus: "Phase 1",
      links: [
        "https://www.genecards.org/cgi-bin/carddisp.pl?gene=IL10",
        "https://www.targetvalidation.org/target/ENSG00000136634",
      ],
    },
    {
      gene: "IL6",
      ensemblId: "ENSG00000136244",
      disease: "Systemic Lupus Erythematosus",
      archVersion: "v2.4",
      swagStrength: 0.93,
      swagScore: 8.94,
      swagScoreNoClin: 8.52,
      pathwayCausal: 0.94,
      genetic: 0.89,
      pathwayGeneral: 0.92,
      clinicalMao: 0.90,
      currentDevStatus: "Phase 3",
      links: [
        "https://www.genecards.org/cgi-bin/carddisp.pl?gene=IL6",
        "https://www.targetvalidation.org/target/ENSG00000136244",
      ],
    },
    {
      gene: "NR3C1",
      ensemblId: "ENSG00000113580",
      disease: "Systemic Lupus Erythematosus",
      archVersion: "v2.4",
      swagStrength: 0.85,
      swagScore: 8.15,
      swagScoreNoClin: 7.74,
      pathwayCausal: 0.88,
      genetic: 0.76,
      pathwayGeneral: 0.87,
      clinicalMao: 0.89,
      currentDevStatus: "Launched",
      links: [
        "https://www.genecards.org/cgi-bin/carddisp.pl?gene=NR3C1",
        "https://www.targetvalidation.org/target/ENSG00000113580",
      ],
    },
  ],
  clinicalTrials: [
    {
      studyNumber: "M14-5521",
      studyTitle:
        "A Multicenter Phase 2 Study Evaluating Upadacitinib in Subjects with Moderately to Severely Active Systemic Lupus Erythematosus",
      therapeuticArea: "Immunology",
      drugName: "Upadacitinib",
      compound: "ABT-494",
      indication: "Systemic Lupus Erythematosus",
      startYear: 2018,
      phase: "Phase 2",
      mainFindings:
        "Achieved primary endpoint of SRI-4 response at week 24 with statistically significant suppression of flare incidence versus standard of care.",
      bottomLine: "Robust clinical efficacy supporting advancement to pivotal Phase 3 trials in SLE.",
      registryUrl: "https://clinicaltrials.gov/study/NCT03978520",
    },
    {
      studyNumber: "M14-5522",
      studyTitle: "Long-Term Extension Study of Upadacitinib in Adult Patients with Systemic Lupus Erythematosus",
      therapeuticArea: "Immunology",
      drugName: "Upadacitinib",
      compound: "ABT-494",
      indication: "Systemic Lupus Erythematosus",
      startYear: 2019,
      phase: "Phase 2",
      mainFindings:
        "Sustained disease control over 52 weeks with acceptable safety profile consistent with known JAK1 selectivity.",
      bottomLine: "Favorable long-term benefit-risk balance established across SLE cohort.",
      registryUrl: "https://clinicaltrials.gov/study/NCT03978520",
    },
    {
      studyNumber: "M14-5623",
      studyTitle:
        "Phase 2 Study to Evaluate Pharmacokinetics, Safety, and Tolerability of ABBV-599 in Refractory Lupus Nephritis",
      therapeuticArea: "Immunology",
      drugName: "Elsubrutinib + Upadacitinib",
      compound: "ABBV-599",
      indication: "Systemic Lupus Erythematosus",
      startYear: 2020,
      phase: "Phase 2",
      mainFindings:
        "Dual BTK/JAK inhibition led to 42% reduction in proteinuria at week 12 compared with baseline.",
      bottomLine: "Proof-of-concept confirmed for dual-targeting strategy in high-need lupus nephritis subpopulation.",
      registryUrl: "https://clinicaltrials.gov/study/NCT03978520",
    },
    {
      studyNumber: "M13-093",
      studyTitle:
        "A Phase 1b Study of ABBV-154, an Antibody-Drug Conjugate Targeting Glucocorticoid Receptor in Healthy Volunteers and Autoimmune Patients",
      therapeuticArea: "Immunology",
      drugName: "ABBV-154",
      compound: "ABBV-154",
      indication: "Systemic Lupus Erythematosus",
      startYear: 2017,
      phase: "Phase 1b",
      mainFindings:
        "Selective delivery of glucocorticoid receptor modulator achieved targeted anti-inflammatory effect with reduced systemic endocrine liabilities.",
      bottomLine: "Demonstrated targeted immunomodulation without classic systemic steroid adverse effects.",
      registryUrl: "https://clinicaltrials.gov/study/NCT03978520",
    },
    {
      studyNumber: "M14-562",
      studyTitle: "Dose-Ranging Phase 2 Trial of Elsubrutinib (ABBV-105) Monotherapy in Moderate-to-Severe SLE",
      therapeuticArea: "Immunology",
      drugName: "Elsubrutinib",
      compound: "ABBV-105",
      indication: "Systemic Lupus Erythematosus",
      startYear: 2019,
      phase: "Phase 2",
      mainFindings: "Dose-dependent inhibition of BTK phosphorylation and B-cell activation markers observed.",
      bottomLine: "Monotherapy showed moderate clinical signal; optimal potency achieved in combination.",
      registryUrl: "https://clinicaltrials.gov/study/NCT03978520",
    },
    {
      studyNumber: "M16-044",
      studyTitle:
        "Phase 2 Study of Upadacitinib vs Placebo in Patients with Moderate-to-Severe Hidradenitis Suppurativa",
      therapeuticArea: "Immunology",
      drugName: "Upadacitinib",
      compound: "ABT-494",
      indication: "Hidradenitis Suppurativa",
      startYear: 2021,
      phase: "Phase 2",
      mainFindings:
        "Statistically significant improvement in HiSCR50 at week 16 (p < 0.001) vs placebo with rapid lesion resolution.",
      bottomLine: "Strong validation of JAK1 pathway inhibition in suppurative inflammatory dermatoses.",
      registryUrl: "https://clinicaltrials.gov/study/NCT03978520",
    },
    {
      studyNumber: "M16-763",
      studyTitle:
        "Phase 3 Pivotal Trial Assessing Long-Term Safety and Efficacy of Upadacitinib in Hidradenitis Suppurativa",
      therapeuticArea: "Immunology",
      drugName: "Upadacitinib",
      compound: "ABT-494",
      indication: "Hidradenitis Suppurativa",
      startYear: 2022,
      phase: "Phase 3",
      mainFindings:
        "Met primary and secondary endpoints; substantial reduction in draining tunnels and pain NRS score.",
      bottomLine: "Pivotal registrational dataset supporting global regulatory filings for HS.",
      registryUrl: "https://clinicaltrials.gov/study/NCT03978520",
    },
    {
      studyNumber: "M23-699",
      studyTitle:
        "Comparative Effectiveness and Biomarker Study of Rinvoq (Upadacitinib) Across Autoimmune Indications",
      therapeuticArea: "Immunology",
      drugName: "Rinvoq (Upadacitinib)",
      compound: "ABT-494",
      indication: "Systemic Lupus Erythematosus",
      startYear: 2023,
      phase: "Phase 3",
      mainFindings:
        "Consistent immune signature downregulation including IFN-alpha and IL-6 downstream transcriptional networks.",
      bottomLine: "Broad therapeutic window established across complex inflammatory phenotypes.",
      registryUrl: "https://clinicaltrials.gov/study/NCT03978520",
    },
    {
      studyNumber: "M25-433",
      studyTitle:
        "Exploratory Phase 1b Multi-Omic Profiling of Oral TYK2 Inhibitors in Refractory Cutaneous Lupus",
      therapeuticArea: "Immunology",
      drugName: "ABBV-TYK2",
      compound: "A-1984701.0",
      indication: "Systemic Lupus Erythematosus",
      startYear: 2024,
      phase: "Phase 1b",
      mainFindings:
        "Potent blockade of IL-12/IL-23 and Type I IFN signaling cascades with high skin-tissue penetration.",
      bottomLine: "Excellent target engagement profile in dermal inflammation and epidermal keratinocyte models.",
      registryUrl: "https://clinicaltrials.gov/study/NCT03978520",
    },
    {
      studyNumber: "M16-356",
      studyTitle:
        "A Phase 2 Double-Blind Placebo-Controlled Study of Anti-IL6 Monoclonal Antibody in Active Lupus Nephritis",
      therapeuticArea: "Immunology",
      drugName: "Sarilumab / ABBV-IL6",
      compound: "ABBV-601",
      indication: "Systemic Lupus Erythematosus",
      startYear: 2020,
      phase: "Phase 2",
      mainFindings:
        "Significant suppression of anti-dsDNA titers and normalization of complement C3/C4 levels.",
      bottomLine:
        "Demonstrated core clinical validation of IL-6 axis neutralization in immune-complex driven disease.",
      registryUrl: "https://clinicaltrials.gov/study/NCT03978520",
    },
    {
      studyNumber: "M19-130",
      studyTitle:
        "A Phase 2 Randomized, Double-Blind, Placebo-Controlled Study to Evaluate the Safety and Efficacy of ABBV-599 (Elsubrutinib and Upadacitinib Co-formulation) in Moderately to Severely Active Systemic Lupus Erythematosus",
      therapeuticArea: "Immunology",
      drugName: "ABBV-599 (Elsubrutinib + Upadacitinib)",
      compound: "ABBV-599",
      indication: "Systemic Lupus Erythematosus",
      startYear: 2019,
      phase: "Phase 2",
      mainFindings:
        "NCT03978520 demonstrated dual BTK/JAK1 inhibition synergistically superior to either monotherapy alone, achieving SRI-4 improvement of 68.2% vs 41.5% placebo at week 24.",
      bottomLine:
        "Flagship combination proof-of-concept demonstrating additive efficacy without non-linear increase in adverse events.",
      registryUrl: "https://clinicaltrials.gov/study/NCT03978520",
    },
    {
      studyNumber: "M20-186",
      studyTitle:
        "Phase 1/2 Biomarker-Driven Basket Trial Evaluating Targeted Immunotherapy Combinations in Severe Autoimmune Diseases",
      therapeuticArea: "Immunology",
      drugName: "ABBV-ComboX",
      compound: "A-2208690.0",
      indication: "Systemic Lupus Erythematosus",
      startYear: 2022,
      phase: "Phase 1/2",
      mainFindings:
        "Combined mTORC1/2 and tyrosine kinase inhibition reduced memory B-cell expansion and hyper-active γδ17 T-cell differentiation.",
      bottomLine: "Clinical translational bridge connecting in vitro repurposing hits to patient biomarker signatures.",
      registryUrl: "https://clinicaltrials.gov/study/NCT03978520",
    },
  ],
  comboMechanisms: [
    {
      moa1: "IL6",
      moa2: "TNFSF13B",
      disease: "Systemic Lupus Erythematosus",
      ta: "Immunology",
      swag1: 8.94,
      swag2: 8.62,
      dualActivity: 8.78,
      expectedResult:
        "Dual blockade of plasma cell survival (BAFF/TNFSF13B) and acute phase IL-6 inflammatory signaling, driving deep remission in autoantibody titers.",
      sabIntact: 0.8,
      compositeAiScore: 7.58,
      toxicityRisk: "Low",
    },
    {
      moa1: "IL6",
      moa2: "TYK2",
      disease: "Systemic Lupus Erythematosus",
      ta: "Immunology",
      swag1: 8.94,
      swag2: 8.75,
      dualActivity: 8.84,
      expectedResult:
        "Simultaneous inhibition of gp130/STAT3 signaling and Type I IFN/IL-12/23 axis via TYK2, providing broad multi-pathway coverage.",
      sabIntact: 0.79,
      compositeAiScore: 7.57,
      toxicityRisk: "Moderate",
    },
    {
      moa1: "IL6",
      moa2: "TNFRSF13C",
      disease: "Systemic Lupus Erythematosus",
      ta: "Immunology",
      swag1: 8.94,
      swag2: 8.12,
      dualActivity: 8.53,
      expectedResult:
        "Complementary suppression of BAFF receptor-mediated mature B-cell survival and IL-6 driven plasmablast differentiation.",
      sabIntact: 0.75,
      compositeAiScore: 7.42,
      toxicityRisk: "Low",
    },
    {
      moa1: "IL6",
      moa2: "NR3C1",
      disease: "Systemic Lupus Erythematosus",
      ta: "Immunology",
      swag1: 8.94,
      swag2: 8.15,
      dualActivity: 8.54,
      expectedResult:
        "Glucocorticoid receptor agonism paired with IL-6 antagonism allows steroid-sparing immunosuppressive efficacy.",
      sabIntact: 0.74,
      compositeAiScore: 7.36,
      toxicityRisk: "Moderate",
    },
    {
      moa1: "IL6",
      moa2: "MS4A1",
      disease: "Systemic Lupus Erythematosus",
      ta: "Immunology",
      swag1: 8.94,
      swag2: 7.95,
      dualActivity: 8.44,
      expectedResult:
        "CD20 B-cell depletion combined with neutralization of IL-6 cytokine storm prevents pathogenic rebound.",
      sabIntact: 0.73,
      compositeAiScore: 7.29,
      toxicityRisk: "Moderate",
    },
    {
      moa1: "IL6",
      moa2: "TNFSF4",
      disease: "Systemic Lupus Erythematosus",
      ta: "Immunology",
      swag1: 8.94,
      swag2: 7.68,
      dualActivity: 8.31,
      expectedResult:
        "OX40L costimulation blockade plus IL-6 inhibition curbs T-follicular helper cell hyperactivity.",
      sabIntact: 0.71,
      compositeAiScore: 7.18,
      toxicityRisk: "Low",
    },
    {
      moa1: "IL6",
      moa2: "JAK3",
      disease: "Systemic Lupus Erythematosus",
      ta: "Immunology",
      swag1: 8.94,
      swag2: 7.82,
      dualActivity: 8.38,
      expectedResult:
        "Suppression of common gamma chain cytokine signaling (IL-2, 4, 7, 9, 15, 21) alongside IL-6/STAT3 pathway.",
      sabIntact: 0.69,
      compositeAiScore: 7.12,
      toxicityRisk: "Moderate",
    },
    {
      moa1: "IL6",
      moa2: "JAK1",
      disease: "Systemic Lupus Erythematosus",
      ta: "Immunology",
      swag1: 8.94,
      swag2: 8.45,
      dualActivity: 8.69,
      expectedResult:
        "Targeted JAK1 kinase inhibition downregulates downstream IL-6 and type I interferon transcriptomic drivers.",
      sabIntact: 0.76,
      compositeAiScore: 7.45,
      toxicityRisk: "Low",
    },
    {
      moa1: "IL6",
      moa2: "NFKB1",
      disease: "Systemic Lupus Erythematosus",
      ta: "Immunology",
      swag1: 8.94,
      swag2: 7.55,
      dualActivity: 8.24,
      expectedResult:
        "Nuclear Factor Kappa B subunit inhibition interrupts core transcriptional amplification of IL-6 and TNF.",
      sabIntact: 0.68,
      compositeAiScore: 7.05,
      toxicityRisk: "Severe",
    },
    {
      moa1: "IL6",
      moa2: "PDE4B",
      disease: "Systemic Lupus Erythematosus",
      ta: "Immunology",
      swag1: 8.94,
      swag2: 7.4,
      dualActivity: 8.17,
      expectedResult:
        "Phosphodiesterase 4B inhibition elevates cAMP, synergizing with IL-6 blockade to suppress macrophage activation.",
      sabIntact: 0.67,
      compositeAiScore: 6.98,
      toxicityRisk: "Low",
    },
    {
      moa1: "IL6",
      moa2: "TGFB1",
      disease: "Systemic Lupus Erythematosus",
      ta: "Immunology",
      swag1: 8.94,
      swag2: 7.32,
      dualActivity: 8.13,
      expectedResult:
        "Balanced TGFB1 modulation and IL-6 neutralization mitigates Th17 skewing while preserving regulatory T-cell homeostasis.",
      sabIntact: 0.65,
      compositeAiScore: 6.89,
      toxicityRisk: "Moderate",
    },
  ],
  preclinicalSample: {
    assayType: "in vitro",
    cellLine: "γδ17 T-cell",
    targetPathway: "IL-23 / mTORC1 / mTORC2 / Src family kinases",
    compoundSource: "FDA-Approved Repurposing Screen",
    modelSystem: "imiquimod-induced skin inflammation",
    routesOfAdmin: ["intraperitoneal", "oral", "topical"],
    validationStatus: "validated in primary cells",
    abstract:
      "We developed an in vitro model using a γδ17 T-cell line to study IL-23 responses and performed a drug-repurposing screen of US Food and Drug Administration-approved compounds. Hits were validated in primary cells. The in vivo efficacy of candidate inhibitors was evaluated in the imiquimod-induced model of skin inflammation via intraperitoneal, oral, and topical administration. Mechanistic studies assessed IL-23-dependent activation of mechanistic target of rapamycin complex 1 (mTORC1) and mTORC2 and the role of Src family kinases.",
    compounds: [
      {
        compoundId: "A-1984701.0",
        compoundName: "A-1984701.0 (AbbVie Lead TYK2/Src Modulator)",
        mechanism: "Selective TYK2 / Src family kinase inhibitor",
        log2FC: -3.85,
        pValue: 0.00012,
        ic50Ip: 12.4,
        ic50Oral: 24.8,
        ic50Topical: 18.2,
        dosageArms: [
          {
            route: "intraperitoneal",
            dose: "5 mg/kg BID",
            ic50: 12.4,
            unit: "nM",
            log2FC: -3.85,
            pValue: 0.00012,
            efficacyPercent: 88.5,
          },
          {
            route: "oral",
            dose: "15 mg/kg QD",
            ic50: 24.8,
            unit: "nM",
            log2FC: -3.42,
            pValue: 0.00028,
            efficacyPercent: 82.1,
          },
          {
            route: "topical",
            dose: "0.5% ointment BID",
            ic50: 18.2,
            unit: "nM",
            log2FC: -3.64,
            pValue: 0.00018,
            efficacyPercent: 85.7,
          },
        ],
        validationNotes:
          "Potently suppressed IL-23-induced STAT3 phosphorylation and IL-17A/F secretion in both γδ17 cell lines and primary dermal γδ T cells.",
      },
      {
        compoundId: "A-2208690.0",
        compoundName: "A-2208690.0 (AbbVie Dual mTORC1/2 & Kinase Probe)",
        mechanism: "Dual mTORC1/mTORC2 catalytic inhibitor",
        log2FC: -3.52,
        pValue: 0.00034,
        ic50Ip: 16.8,
        ic50Oral: 31.5,
        ic50Topical: 22.0,
        dosageArms: [
          {
            route: "intraperitoneal",
            dose: "10 mg/kg QD",
            ic50: 16.8,
            unit: "nM",
            log2FC: -3.52,
            pValue: 0.00034,
            efficacyPercent: 84.2,
          },
          {
            route: "oral",
            dose: "25 mg/kg QD",
            ic50: 31.5,
            unit: "nM",
            log2FC: -3.1,
            pValue: 0.00072,
            efficacyPercent: 77.4,
          },
          {
            route: "topical",
            dose: "1.0% cream BID",
            ic50: 22.0,
            unit: "nM",
            log2FC: -3.31,
            pValue: 0.00045,
            efficacyPercent: 80.9,
          },
        ],
        validationNotes:
          "Completely ablated p-S6 (mTORC1) and p-Akt Ser473 (mTORC2) upon IL-23 stimulation, blocking γδ17 clonal proliferation.",
      },
      {
        compoundId: "Rapamycin",
        compoundName: "Rapamycin (Sirolimus)",
        mechanism: "Allosteric mTORC1 inhibitor",
        log2FC: -2.94,
        pValue: 0.0011,
        ic50Ip: 28.5,
        ic50Oral: 54.2,
        ic50Topical: 41.0,
        dosageArms: [
          {
            route: "intraperitoneal",
            dose: "2 mg/kg QD",
            ic50: 28.5,
            unit: "nM",
            log2FC: -2.94,
            pValue: 0.0011,
            efficacyPercent: 73.6,
          },
          {
            route: "oral",
            dose: "5 mg/kg QD",
            ic50: 54.2,
            unit: "nM",
            log2FC: -2.48,
            pValue: 0.0024,
            efficacyPercent: 66.8,
          },
          {
            route: "topical",
            dose: "0.2% gel QD",
            ic50: 41.0,
            unit: "nM",
            log2FC: -2.71,
            pValue: 0.0016,
            efficacyPercent: 70.1,
          },
        ],
        validationNotes:
          "Partial inhibition of IL-23 signaling; feedback activation of Akt observed in primary cells at lower concentrations.",
      },
      {
        compoundId: "Tofacitinib",
        compoundName: "Tofacitinib",
        mechanism: "Pan-JAK inhibitor (JAK1/JAK3 > JAK2)",
        log2FC: -3.28,
        pValue: 0.00058,
        ic50Ip: 21.0,
        ic50Oral: 38.0,
        ic50Topical: 29.5,
        dosageArms: [
          {
            route: "intraperitoneal",
            dose: "10 mg/kg BID",
            ic50: 21.0,
            unit: "nM",
            log2FC: -3.28,
            pValue: 0.00058,
            efficacyPercent: 79.8,
          },
          {
            route: "oral",
            dose: "20 mg/kg BID",
            ic50: 38.0,
            unit: "nM",
            log2FC: -2.88,
            pValue: 0.0012,
            efficacyPercent: 72.5,
          },
          {
            route: "topical",
            dose: "2.0% ointment BID",
            ic50: 29.5,
            unit: "nM",
            log2FC: -3.05,
            pValue: 0.00085,
            efficacyPercent: 76.2,
          },
        ],
        validationNotes:
          "Suppresses downstream IL-23 receptor signaling and epidermal acanthosis in the imiquimod mouse skin inflammation model.",
      },
      {
        compoundId: "Dasatinib",
        compoundName: "Dasatinib",
        mechanism: "Broad-spectrum BCR-ABL and Src family kinase inhibitor",
        log2FC: -3.61,
        pValue: 0.00021,
        ic50Ip: 14.2,
        ic50Oral: 27.6,
        ic50Topical: 19.8,
        dosageArms: [
          {
            route: "intraperitoneal",
            dose: "5 mg/kg QD",
            ic50: 14.2,
            unit: "nM",
            log2FC: -3.61,
            pValue: 0.00021,
            efficacyPercent: 86.4,
          },
          {
            route: "oral",
            dose: "10 mg/kg QD",
            ic50: 27.6,
            unit: "nM",
            log2FC: -3.25,
            pValue: 0.00049,
            efficacyPercent: 79.6,
          },
          {
            route: "topical",
            dose: "0.5% lotion BID",
            ic50: 19.8,
            unit: "nM",
            log2FC: -3.48,
            pValue: 0.00031,
            efficacyPercent: 83.9,
          },
        ],
        validationNotes:
          "Identified Src family kinase (Lck/Fyn) activation as critical upstream regulator of IL-23 receptor complex assembly in γδ17 T-cells.",
      },
    ],
  },
  provenanceRecords: [
    {
      sourceDocId: "ELN-IMM-2024-089",
      docTitle: "High-Throughput Repurposing Screen of FDA Approved Compounds in γδ17 T-Cell Lines",
      docType: "ELN",
      snippet:
        "Screening of 1,280 FDA-approved compounds in IL-23 stimulated γδ17 T-cells identified A-1984701.0 and Dasatinib as primary hits with log2FC < -3.5.",
      pageNumber: 14,
      boundingBox: {
        x1: 0.12,
        y1: 0.25,
        x2: 0.88,
        y2: 0.42,
      },
      confidenceScore: 0.98,
    },
    {
      sourceDocId: "CSR-M19-130-P2",
      docTitle: "Clinical Study Report: ABBV-599 Phase 2 in SLE (NCT03978520)",
      docType: "CSR",
      snippet:
        "Co-formulation of elsubrutinib and upadacitinib met primary endpoint with 68.2% SRI-4 response at Week 24 vs 41.5% placebo (p=0.003).",
      pageNumber: 48,
      boundingBox: {
        x1: 0.1,
        y1: 0.15,
        x2: 0.9,
        y2: 0.35,
      },
      confidenceScore: 0.99,
    },
    {
      sourceDocId: "PUB-34982103",
      docTitle: "Targeting mTORC1/2 and Src Kinases in IL-23 Driven Skin Inflammation",
      docType: "PubMed",
      snippet:
        "Evaluation of topical and oral formulations in imiquimod-induced skin inflammation confirmed potent reduction in dermal ear swelling and IL-17 cytokine release.",
      pageNumber: 7,
      boundingBox: {
        x1: 0.15,
        y1: 0.3,
        x2: 0.85,
        y2: 0.55,
      },
      confidenceScore: 0.96,
    },
    {
      sourceDocId: "ONT-IDMP-IMM-04",
      docTitle: "IDMP Ontology Mapping for SLE & HS Combination Targets",
      docType: "IDMP-Ontology",
      snippet:
        "Cross-ontology mapping harmonizing IL6, TYK2, and TNFSF13B across MeSH, MedDRA, and Ensembl disease-target annotations.",
      pageNumber: 2,
      boundingBox: {
        x1: 0.05,
        y1: 0.1,
        x2: 0.95,
        y2: 0.28,
      },
      confidenceScore: 0.95,
    },
    {
      sourceDocId: "SOP-ASSAY-772",
      docTitle: "Standard Operating Procedure: Primary γδ T-cell Flow Cytometry and Phosphorylation Assays",
      docType: "SOP",
      snippet:
        "Protocols for gating CD3+ TCRgd+ IL-23R+ subsets and quantifying p-STAT3, p-S6, and p-Src upon ligand stimulation.",
      pageNumber: 5,
      boundingBox: {
        x1: 0.08,
        y1: 0.4,
        x2: 0.92,
        y2: 0.7,
      },
      confidenceScore: 0.97,
    },
  ],
  threads: [
    {
      threadId: "TH-2026-001",
      title: "IL-6 Synergy & γδ17 Screen Exploration",
      createdAt: "2026-08-06T10:00:00Z",
      updatedAt: "2026-08-06T10:30:00Z",
      clarificationTurnCount: 0,
      messages: [
        {
          id: "msg-001",
          role: "user",
          content: "What are the top combination targets for IL-6 in Systemic Lupus Erythematosus based on ARCH SWAG scores?",
          timestamp: "2026-08-06T10:00:05Z",
          provenance: [],
        },
        {
          id: "msg-002",
          role: "assistant",
          content:
            "Based on the ARCH v2.4 dataset (Slide 16), the top combinations with IL-6 are TNFSF13B (Composite Score 7.58, sAB intact 0.80) and TYK2 (Composite Score 7.57, sAB intact 0.79), followed by TNFRSF13C and NR3C1.",
          timestamp: "2026-08-06T10:00:15Z",
          provenance: [
            {
              sourceDocId: "ONT-IDMP-IMM-04",
              docTitle: "IDMP Ontology Mapping for SLE & HS Combination Targets",
              docType: "IDMP-Ontology",
              snippet:
                "Cross-ontology mapping harmonizing IL6, TYK2, and TNFSF13B across MeSH, MedDRA, and Ensembl disease-target annotations.",
              pageNumber: 2,
              boundingBox: {
                x1: 0.05,
                y1: 0.1,
                x2: 0.95,
                y2: 0.28,
              },
              confidenceScore: 0.95,
            },
          ],
        },
      ],
    },
  ],
};
